import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import Plot from '../component/Plot';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        {/* <script src="https://unpkg.com/konva@8.3.5/konva.min.js"></script> */}
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <Plot />
      </main>
    </div>
  );
}
