import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import { useSelector } from "react-redux";

import PlotCard from '../component/PlotCard';
// import 'dotenv/config'

export default function Home() {
  const { address, isLoggedIn } = useSelector((state) => state.user);
  return (
    <div className={styles.container}>
      <Head>
        <title>CornerStone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {isLoggedIn && (
          <div className="">
            <p class="h5 mb-3">{`Hey ${address}`}</p>

            <h1 className={styles.title}>
              Welcome to <a href="https://nextjs.org">CornerStone!</a>
            </h1>
          </div>
        )}
        {/* <PlotCard /> */}
      </main>
    </div>
  );
}
